### ISSUE TITLE
Please consider adding a donation link

### ISSUE THREAD

**Issue by castrojo** [lancachenet/lancachenet.github.io#3]
Your tools have helped save so much time for our group I'd like to send donations, something similar to "A portion of your LAN party fee will be donated to the OSS infrastructure projects we use." 

Thanks!

**Comment by astrolox** [comment]
To be considered. Thanks for the suggestion.

**Comment by astrolox** [comment]
We are now accepting donations through [ko-fi](https://ko-fi.com/lancachenet). Other options may open up in the future but this seemed the most suitable for the time being. **Thanks for the suggestion!**

https://ko-fi.com/lancachenet
